---
ansible_connection: local

kiali_namespace: kiali-operator

kiali:
  NAMESPACE: "{{ kiali_namespace }}"
  NAMESPACE_DISPLAY_NAME: "{{ kiali_namespace }}"

openshift_cluster_content:
- object: kiali-operator
  content:
  - name: "{{ kiali_namespace }}"
    template: "https://raw.githubusercontent.com/redhat-cop/openshift-templates/master/project-requests/create-project.yml"
    params_from_vars: "{{ kiali }}"
    action: create
    tags:
    - "{{ kiali_namespace }}"
    - projects
    - "projects-{{ kiali_namespace }}"
  - name: kiali-operator
    file: "{{ playbook_dir }}/templates/kiali/operator_install.yaml"
    namespace: "{{ kiali_namespace }}"
    tags:
    - kiali-operator
